version: '3'
networks:
    app-network:
      driver: bridge
  
services:
    nodejs:
        build:
            context: ./web
        image: nodejs
        container_name: nodejs
        restart: unless-stopped
        networks:
        - app-network

    nginx:
        image: nginx:mainline-alpine
        container_name: webserver
        build:
            context: ./nginx
        restart: unless-stopped
        ports:
        - "8888:80"
        depends_on:
        - nodejs
        networks:
        - app-network